version: '3'

services:
  nginx:
    image: nginx:mainline-alpine3.18-slim
    container_name: WebServer
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/certs:/etc/nginx/certs
    networks:
      default:
        ipv4_address: 172.18.0.2

  frontend:
    build: ./1D-Chess-2.0-Frontend
    container_name: ReactFrontend
    networks:
      default:
        ipv4_address: 172.18.0.3
    volumes:
      - ./1D-Chess-2.0-Frontend:/frontend/1D-Chess-2.0-Frontend:rw
    environment:
      ENV: dev